### PR TITLE
Disk Functions Added

### PR DESCRIPTION
**Pull request by istairbn**
Get-WAPVMRoleVMDisk : Fetches all Disks currently attached to a WAPVMRoleVM. Returns WAP.DISK objects
Expand-WAPVMRoleVMDisk: Takes a WAP.DISK Object a size in GB, expands the disk to the requested size.
Invoke-WAPVMRoleVMDiskExpansion: Takes a WAP.DISK Object a size in GB. This stops the VM, Invokes the epansion command and then restarts the VM. 

Get-WAPVMRoleDisk: Fetches all Disks in the subscription. Returns WAP.DISKIMAGE Objects
New-WAPVMRoleVMDisk: Takes a WAP.DISKIMAGE object and a Cloud Service Name, then mounts attaches the Disk to the VM.

### CODE REVIEW

**Comment by bgelens** [comment]
Thanks for the contribution. I'm not able to verify your code as I'm in lack of an Azure Pack environment.
Are you planning on adding more code in the future? I could add you as a contributor so you can merge your own PRs.

**Comment by istairbn** [comment]
Hi Ben,

Hope you're keeping well! Seeing as more and more Rabo teams keep needing it, I'm sure more requests will come in eventually. 

I've got a second module for stuff that's Rabo specific, but anything valuable to general users I'll push here. 

Best, 
Ben N

**Comment by bgelens** [comment]
Hi Ben, I've added you as a collaborator for this repo. Meaning you are able to merge / push yourself.
Please keep using the PR mechanism and go ahead and merge yourself.

**Comment by bgelens** [comment]
@istairbn 👍

**Pull request merged**
